/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminSidebar: typeof import('./src/components/AdminSidebar.vue')['default']
    AdminTopbar: typeof import('./src/components/AdminTopbar.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    GlobalSearch: typeof import('./src/components/GlobalSearch.vue')['default']
    GradientPicker: typeof import('./src/components/GradientPicker.vue')['default']
    ModalDialog: typeof import('./src/components/ModalDialog.vue')['default']
    NewsForm: typeof import('./src/components/NewsForm.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./src/components/StatCard.vue')['default']
    StatusBadge: typeof import('./src/components/StatusBadge.vue')['default']
  }
}
