/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/audit': RouteRecordInfo<
      '/audit',
      '/audit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories': RouteRecordInfo<
      '/categories',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/comments': RouteRecordInfo<
      '/comments',
      '/comments',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/news/': RouteRecordInfo<
      '/news/',
      '/news',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/news/[id]': RouteRecordInfo<
      '/news/[id]',
      '/news/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/news/new': RouteRecordInfo<
      '/news/new',
      '/news/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/users': RouteRecordInfo<
      '/users',
      '/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
      pathParamNames:
        | 'all'
    }
    'src/pages/audit.vue': {
      routes:
        | '/audit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/categories.vue': {
      routes:
        | '/categories'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/comments.vue': {
      routes:
        | '/comments'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/news/index.vue': {
      routes:
        | '/news/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/news/[id].vue': {
      routes:
        | '/news/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/news/new.vue': {
      routes:
        | '/news/new'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/users.vue': {
      routes:
        | '/users'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
